apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: envoy
data:
  envoy.yaml: |
    static_resources:
      listeners:
      # HTTP Listener
      - name: listener_http
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: auth_service
                  domains: ["auth-service.envoy.svc.cluster.local"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: auth_service_cluster
                - name: external
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: dynamic_forward_proxy_cluster
                      timeout: 15s
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  transport_api_version: V3
                  http_service:
                    server_uri:
                      uri: http://auth-service.envoy.svc.cluster.local:8081/check
                      cluster: auth_service_cluster
                      timeout: 5s
                    authorization_request:
                      allowed_headers:
                        patterns:
                        - exact: "host"
                        - exact: ":method"
                        - exact: ":path"
                        - exact: ":authority"
                        - exact: "content-type"
                        - prefix: "x-forwarded-"
                        - prefix: "user-agent"
                        - prefix: "authorization"
                        - prefix: "proxy-"
                    authorization_response:
                      allowed_upstream_headers:
                        patterns:
                        - exact: "x-auth-header"
                        - prefix: "x-auth-"
                      allowed_client_headers:
                        patterns:
                        - exact: "x-auth-header"
                        - prefix: "x-auth-"
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    name: dynamic_forward_proxy_cache_config
                    dns_lookup_family: V4_ONLY
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      # HTTPS Listener with CONNECT support
      - name: listener_https
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 443
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_https
              codec_type: AUTO
              normalize_path: false
              use_remote_address: true
              path_with_escaped_slashes_action: KEEP_UNCHANGED
              route_config:
                name: https_route
                virtual_hosts:
                - name: https_proxy
                  domains: ["*"]
                  routes:
                  - match:
                      connect_matcher: {}
                    route:
                      cluster: dynamic_forward_proxy_cluster
                      upgrade_configs:
                        - upgrade_type: CONNECT
                          enabled: true
                      max_stream_duration:
                        grpc_timeout_header_max: 0s
                        max_stream_duration: 0s
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  transport_api_version: V3
                  http_service:
                    server_uri:
                      uri: http://auth-service.envoy.svc.cluster.local:8081/check
                      cluster: auth_service_cluster
                      timeout: 5s
                    authorization_request:
                      allowed_headers:
                        patterns:
                        - exact: "host"
                        - exact: ":method"
                        - exact: ":path"
                        - exact: ":authority"
                        - exact: "content-type"
                        - prefix: "x-forwarded-"
                        - prefix: "user-agent"
                        - prefix: "authorization"
                        - prefix: "proxy-"
                        - exact: "proxy-connection"
                    authorization_response:
                      allowed_upstream_headers:
                        patterns:
                        - exact: "x-auth-header"
                        - prefix: "x-auth-"
                      allowed_client_headers:
                        patterns:
                        - exact: "x-auth-header"
                        - prefix: "x-auth-"
                  failure_mode_allow: true
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    name: dynamic_forward_proxy_cache_config
                    dns_lookup_family: V4_ONLY
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
      - name: dynamic_forward_proxy_cluster
        connect_timeout: 1s
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              name: dynamic_forward_proxy_cache_config
              dns_lookup_family: V4_ONLY
            allow_insecure_cluster_options: true

      - name: auth_service_cluster
        connect_timeout: 1s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: auth_service_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: auth-service.envoy.svc.cluster.local
                    port_value: 8081

    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
