apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: envoy
  labels:
    app: envoy
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
