apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
  name: auth-service
  namespace: envoy
spec:
  clusterIP: 10.96.133.54
  clusterIPs:
  - 10.96.133.54
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
  selector:
    app: auth-service
